### PR TITLE
Add missing license

### PR DESCRIPTION
**Pull request by phanect**
Clearly declared license.

### CODE REVIEW

**Comment by phanect** [comment]
@mde I'm using this for my corporate project, so I need clear license declaration. Can you confirm this?

**Comment by phanect** [comment]
@tbjers @4larzconwell @3djensen47 @2kengoldfarb I think all contributors' agreement for this.
Is it OK to license geddy-passport under Apache License v2?

**Comment by mde** [comment]
There is clear license messaging in the README and in all the source code. Geddy has always been Apache 2 license. But I'm happy to add the line into the package.json as well. Thanks!

**Comment by phanect** [comment]
Oh, then I may missed it. Sorry :P

**Comment by mde** [comment]
No worries. Thank for the patch!

**Pull request merged**
